spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_db
    username: restaurant_user
    password: restaurant_password
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  main:
    web-application-type: servlet

legacy:
  console:
    enabled: false

